// src/lib/InkObject/InkObject.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import {
    createInkObject,
    type InkObjectInstance,
    type InkObjectOptions,
  } from "./InkObjectVanilla";

  interface Props extends InkObjectOptions {
    class?: string;
  }

  let { class: className = "", ...options }: Props = $props();

  let canvasEl = $state<HTMLCanvasElement>()!;
  let instance: InkObjectInstance | null = null;

  onMount(() => {
    instance = createInkObject({ canvas: canvasEl }, options);
    return () => {
      instance?.destroy();
      instance = null;
    };
  });

  $effect(() => {
    instance?.setOptions({ ...options });
  });
</script>

<div class={className} style="position: relative;">
  <canvas
    bind:this={canvasEl}
    style="position: absolute; inset: 0; width: 100%; height: 100%; display: block; touch-action: none;"
  ></canvas>
</div>

// src/lib/InkObject/InkObject.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";

import {
  createInkObject,
  type InkObjectInstance,
  type InkObjectOptions,
} from "./InkObjectVanilla";

const props = defineProps<InkObjectOptions>();

const canvasEl = ref<HTMLCanvasElement | null>(null);

let instance: InkObjectInstance | null = null;

onMounted(() => {
  if (canvasEl.value) {
    instance = createInkObject({ canvas: canvasEl.value }, props);
  }
});

onBeforeUnmount(() => {
  instance?.destroy();
  instance = null;
});

watch(
  () => ({ ...props }),
  (next) => instance?.setOptions(next),
  { deep: true },
);
</script>

<template>
  <div style="position: relative">
    <canvas
      ref="canvasEl"
      style="
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        display: block;
        touch-action: none;
      "
    />
  </div>
</template>
